global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'control-plane'
    static_configs:
      - targets: ['control-plane:8000']

  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8001']

  - job_name: 'reporting'
    static_configs:
      - targets: ['reporting:8002']

  - job_name: 'data-manager'
    static_configs:
      - targets: ['data-manager:8003']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
