apiVersion: v2
name: qatron
description: QAtron QA automation platform
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 11.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 17.15.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
